/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-15 08:29:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import dto.KinnImage;
import dto.ImageRepository;

public final class pinterres_005fend_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dto.KinnImage");
    _jspx_imports_classes.add("dto.ImageRepository");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html> \r\n");
      out.write("<html> \r\n");
      out.write("<head> \r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <title>HTML5 with Hanbit</title> \r\n");
      out.write("    <!-- 초기화 -->\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0; padding: 0;\r\n");
      out.write("            font-family: 'Malgun Gotic', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a { text-decoration: none; }\r\n");
      out.write("        img { border: 0; }\r\n");
      out.write("        li { list-style: none; }\r\n");
      out.write("        html { background: #f7f5f5; }\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- 헤더 -->\r\n");
      out.write("    <style>\r\n");
      out.write("        #main-header {\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            background: #faf7f7;\r\n");
      out.write("\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header-search-form {\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header-title {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 200px; height:  40px;\r\n");
      out.write("            left: 50%; margin-left: -100px;\r\n");
      out.write("            background: url('./images/logo.png');\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("\r\n");
      out.write("            text-indent: -9999px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header-menu {\r\n");
      out.write("            float: right;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- 드롭다운 -->\r\n");
      out.write("    <style>\r\n");
      out.write("        .outer-menu {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 100px; height: 20px;\r\n");
      out.write("            line-height: 20px;\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("\r\n");
      out.write("            z-index: 9999;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .outer-menu:hover { background: #E1DFDF; }\r\n");
      out.write("\r\n");
      out.write("        .inner-menu {\r\n");
      out.write("            display: none;\r\n");
      out.write("            background: #FFFFFF;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("\r\n");
      out.write("            border-top: 1px solid #cccaca;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(34,25,25,0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .inner-menu a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 5px 10px;\r\n");
      out.write("            z-index: 5000;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .inner-menu a:hover { background: #E1DFDF; }\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- 네비게이션 메뉴 -->\r\n");
      out.write("    <style>\r\n");
      out.write("        #main-navigation {\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            background: #faf7f7;\r\n");
      out.write("            border-top: 1px solid #cfcaca;\r\n");
      out.write("            box-shadow: 1px 3px 3px rgba(34, 25, 25, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #main-navigation > ul {\r\n");
      out.write("            overflow:hidden;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #main-navigation > ul > li {\r\n");
      out.write("            display: inline;\r\n");
      out.write("\r\n");
      out.write("            padding: 0 5px;\r\n");
      out.write("\r\n");
      out.write("            line-height: 30px;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            color: #524D4D;\r\n");
      out.write("            text-shadow: 0 1px 1px white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #main-navigation > ul > li:hover { \r\n");
      out.write("            background: #E1DFDF;\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- 검색 양식 -->\r\n");
      out.write("    <style>\r\n");
      out.write("        .header-search-form {\r\n");
      out.write("            height: 26px;\r\n");
      out.write("            padding: 7px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-search {\r\n");
      out.write("            display: block;\r\n");
      out.write("            float: left;\r\n");
      out.write("\r\n");
      out.write("            background-color: #FFFFFF;\r\n");
      out.write("            border: 1px solid #CCCCCC;\r\n");
      out.write("            border-radius: 15px 0 0 15px;\r\n");
      out.write("            box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);\r\n");
      out.write("\r\n");
      out.write("            width: 120px; height: 24px;\r\n");
      out.write("            padding: 0 0 0 10px;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            color: #555555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-search:focus {\r\n");
      out.write("            border-color: rgba(82, 168, 236, 0.8);\r\n");
      out.write("            outline: 0;\r\n");
      out.write("            box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-search-submit {\r\n");
      out.write("            display: block;\r\n");
      out.write("            float: left;\r\n");
      out.write("\r\n");
      out.write("            width: 50px; height: 26px;\r\n");
      out.write("            border-radius: 0 15px 15px 0;\r\n");
      out.write("            border: 1px solid #CCCCCC;\r\n");
      out.write("\r\n");
      out.write("            margin-left: -1px;\r\n");
      out.write("\r\n");
      out.write("            vertical-align: top;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- 종이 스타일 -->\r\n");
      out.write("    <style>\r\n");
      out.write("        .paper {\r\n");
      out.write("            width: 190px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            padding: 15px 15px 0;\r\n");
      out.write("            font-size: 11px;\r\n");
      out.write("            background: #FFFFFF;\r\n");
      out.write("            box-shadow: 0 1px 3px rgba(34, 25, 25, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .paper-content {\r\n");
      out.write("            margin: 0 -15px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            background: #F2F0F0;\r\n");
      out.write("\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .paper-description {\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .paper-link {\r\n");
      out.write("            display: block;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .paper-text {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 150px;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- 섹션 -->\r\n");
      out.write("    <style>\r\n");
      out.write("        /* 미디어 쿼리를 지원하지 않는 웹 브라우저 */\r\n");
      out.write("        #main-section {\r\n");
      out.write("            width: 920px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 3줄 */\r\n");
      out.write("        @media (max-width: 919px) {\r\n");
      out.write("            #main-section { width: 690px; }\r\n");
      out.write("        } \r\n");
      out.write("\r\n");
      out.write("        /* 4줄 */\r\n");
      out.write("        @media (min-width: 920px) and (max-width:1149px) {\r\n");
      out.write("            #main-section { width: 920px; }\r\n");
      out.write("        } \r\n");
      out.write("\r\n");
      out.write("        /* 5줄 */\r\n");
      out.write("        @media (min-width:1150px) and (max-width:1379px) {\r\n");
      out.write("            #main-section { width: 1150px; }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 6줄 */\r\n");
      out.write("        @media (min-width:1380px) {\r\n");
      out.write("            #main-section { width: 1380px; }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- 라이트박스 -->\r\n");
      out.write("    <style>\r\n");
      out.write("        #darken-background {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0; left: 0; right: 0;\r\n");
      out.write("            height: 100%; \r\n");
      out.write("\r\n");
      out.write("            display: none;\r\n");
      out.write("            background: rgba(0, 0, 0, 0.9);\r\n");
      out.write("            z-index: 10000;\r\n");
      out.write("            overflow-y: scroll;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #lightbox {\r\n");
      out.write("            width: 700px;\r\n");
      out.write("            margin: 20px auto; padding: 15px;\r\n");
      out.write("\r\n");
      out.write("            border: 1px solid #333333;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            box-shadow: 0 5px 5px rgba(34, 25, 25, 0.4);\r\n");
      out.write("\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-information {  overflow: hidden;  text-align: left; }\r\n");
      out.write("        .user-information-image { float: left; width: 70px; }\r\n");
      out.write("        .user-information-text { float: right; width: 620px;  }\r\n");
      out.write("        .lightbox-splitter { margin: 10px 0; }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js\"></script>\r\n");
      out.write("  <!--script src=\"./js/jquery.masonry.min.js\"></script>\r\n");
      out.write("    <script src=\"./js/jquery.imagesloaded.min.js\"></script>-->\r\n");
      out.write("    <script src=\"https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        // 풀다운 메뉴\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            // 풀다운 메뉴\r\n");
      out.write("            $('.outer-menu').hover(function () {\r\n");
      out.write("                $(this).find('.inner-menu').css('display', 'block');\r\n");
      out.write("            }, function () {\r\n");
      out.write("                $(this).find('.inner-menu').css('display', 'none');\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 페이지\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            // 이미지 로드 확인\r\n");
      out.write("            $('#main-section').imagesLoaded(function () {\r\n");
      out.write("                // jQuery Masonry 플러그인 적용\r\n");
      out.write("                $('#main-section').masonry({\r\n");
      out.write("                    itemSelector: '.paper',\r\n");
      out.write("                    columnWidth: 230,\r\n");
      out.write("                    isAnimated: true\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("});\r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("        // 라이트 박스\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            function showLightBox() {\r\n");
      out.write("                // 라이트박스를 보이게 합니다.\r\n");
      out.write("                $('#darken-background').show();\r\n");
      out.write("                $('#darken-background').css('top', $(window).scrollTop());\r\n");
      out.write("                // 스크롤을 못하게 합니다.\r\n");
      out.write("                $('body').css('overflow', 'hidden');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function hideLightBox() {\r\n");
      out.write("                // 라이트박스를 안 보이게 합니다.\r\n");
      out.write("                $('#darken-background').hide();\r\n");
      out.write("\r\n");
      out.write("                // 스크롤을 하게 합니다.\r\n");
      out.write("                $('body').css('overflow', '');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // 라이트박스 제거 이벤트\r\n");
      out.write("            $('#darken-background').click(function () {\r\n");
      out.write("                hideLightBox();\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("              // 클릭 이벤트 연결\r\n");
      out.write("            $('.paper').click(function () {\r\n");
      out.write("                showLightBox();\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // 라이트박스 제거 이벤트 보조\r\n");
      out.write("            $('#lightbox').click(function (event) {\r\n");
      out.write("                event.stopPropagation()\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head> \r\n");
      out.write("<body> \r\n");
      out.write("    <!-- 헤더 --> \r\n");
      out.write("    <header id=\"main-header\"> \r\n");
      out.write("        <div class=\"header-search-form\"> \r\n");
      out.write("            <form> \r\n");
      out.write("                <input type=\"search\" class=\"input-search\" /> \r\n");
      out.write("                <input type=\"submit\" class=\"input-search-submit\" value=\"검색\" /> \r\n");
      out.write("            </form> \r\n");
      out.write("        </div> \r\n");
      out.write("        <h1 class=\"header-title\">Interest</h1> \r\n");
      out.write("        <div class=\"header-menu\"> \r\n");
      out.write("            <ul class=\"outer-menu\"> \r\n");
      out.write("                <li> \r\n");
      out.write("                    <a href=\"#\">정보</a> \r\n");
      out.write("                    <ul class=\"inner-menu\"> \r\n");
      out.write("                        <li><a href=\"#\">데이터</a></li> \r\n");
      out.write("                        <li><a href=\"#\">데이터</a></li> \r\n");
      out.write("                        <li><a href=\"#\">데이터</a></li> \r\n");
      out.write("                        <li><a href=\"#\">데이터</a></li> \r\n");
      out.write("                        <li><a href=\"#\">데이터</a></li> \r\n");
      out.write("                        <li><a href=\"#\">데이터</a></li> \r\n");
      out.write("                    </ul> \r\n");
      out.write("                </li> \r\n");
      out.write("            </ul> \r\n");
      out.write("            <ul class=\"outer-menu\"> \r\n");
      out.write("                <li> \r\n");
      out.write("                    <a href=\"#\">사용자</a> \r\n");
      out.write("                    <ul class=\"inner-menu\"> \r\n");
      out.write("                        <li><a href=\"#\">데이터</a></li> \r\n");
      out.write("                        <li><a href=\"#\">데이터</a></li> \r\n");
      out.write("                        <li><a href=\"#\">데이터</a></li> \r\n");
      out.write("                        <li><a href=\"#\">데이터</a></li> \r\n");
      out.write("                    </ul> \r\n");
      out.write("                </li> \r\n");
      out.write("            </ul> \r\n");
      out.write("        </div> \r\n");
      out.write("    </header> \r\n");
      out.write("    <!-- 네비게이션 메뉴 --> \r\n");
      out.write("    <nav id=\"main-navigation\"> \r\n");
      out.write("        <ul> \r\n");
      out.write("            <li><a href=\"#\">Following</a></li> \r\n");
      out.write("            <li><a href=\"#\">Categories</a></li> \r\n");
      out.write("            <li><a href=\"#\">Everything</a></li> \r\n");
      out.write("            <li><a href=\"#\">Popular</a></li> \r\n");
      out.write("            <li><a href=\"#\">Gift</a></li> \r\n");
      out.write("        </ul> \r\n");
      out.write("    </nav> \r\n");
      out.write("    <!-- 본문 영역 --> \r\n");
      out.write("    <section id=\"main-section\"> \r\n");
       
     ImageRepository repository =  ImageRepository.getInstance();
	 List<KinnImage>  list =repository.getImageList();
	 for(KinnImage image:list){ 
      out.write("\r\n");
      out.write("        <div class=\"paper\"> \r\n");
      out.write("            <div class=\"paper-holder\"> \r\n");
      out.write("                <a><img width=\"190\" src=\"");
      out.print(image.getSrc());
      out.write("\"/></a> \r\n");
      out.write("            </div> \r\n");
      out.write("            <p class=\"paper-description\">");
      out.print(image.getDescription() );
      out.write("</p> \r\n");
      out.write("            <div class=\"paper-content\"> \r\n");
      out.write("                <a class=\"paper-link\" href=\"#\"><img src=\"");
      out.print(image.getPaperLink() );
      out.write("\" /></a> \r\n");
      out.write("                <p class=\"paper-text\">");
      out.print(image.getPaperText() );
      out.write("</p> \r\n");
      out.write("            </div> \r\n");
      out.write("        </div>\r\n");
      out.write("    ");
     
	 }          

      out.write("         \r\n");
      out.write("    </section> \r\n");
      out.write("    <!-- 라이트박스 --> \r\n");
      out.write("    <div id=\"darken-background\"> \r\n");
      out.write("        <div id=\"lightbox\"> \r\n");
      out.write("            <div class=\"user-information\"> \r\n");
      out.write("                <a class=\"user-information-image\" href=\"#\">\r\n");
      out.write("                    <img src=\"http://placekitten.com/70/70\" />\r\n");
      out.write("                </a> \r\n");
      out.write("                <div class=\"user-information-text\">\r\n");
      out.write("                    <h3>User</h3>\r\n");
      out.write("                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sem mi, egestas a facilisis eget, egestas ut magna.</p>\r\n");
      out.write("                </div> \r\n");
      out.write("            </div>\r\n");
      out.write("            <hr class=\"lightbox-splitter\" />\r\n");
      out.write("            <img src=\"http://placekitten.com/600/750\" /> \r\n");
      out.write("        </div> \r\n");
      out.write("    </div> \r\n");
      out.write("</body> \r\n");
      out.write("</html> \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
